const PROJECTS = [
  {
    title: "Financial Complaints Dashboard",
    description: "Tableau dashboard tracking complaint volume, responsiveness, no-cost resolutions, issue categories, and regional trends to surface service pain points and operational bottlenecks.",
    image: "images/1.jpg",
    tags: ["Tableau", "Financial KPIs", "Dashboarding"],
    link: "https://public.tableau.com/app/profile/pallavi.singh3289/viz/FINANCIALCOMPLAINTSDASHBOARD_16485122985760/Dashboard1",
    linkLabel: "View on Tableau Public",
  },
  {
    title: "Customer Spending by Generation",
    description: "Customer behavior analysis highlighting spending differences by income, retention, and product preference to identify the drivers of engagement and revenue concentration.",
    image: "images/Data exploration.jpg",
    tags: ["Tableau", "Customer Analytics"],
    link: "https://public.tableau.com/app/profile/pallavi.singh3289/viz/ConsumerspendingbyGeneration_16491169876090/Dashboard1",
    linkLabel: "View on Tableau Public",
  },
  {
    title: "Invoice & Workforce Hours Dashboard",
    description: "Interactive dashboard for invoice and timesheet analysis, combining KPI summaries, weekly overtime checks, and daily amount alerts to support stronger cost control and operational review.",
    icon: "📊",
    tags: ["JavaScript", "Chart.js", "Data Viz"],
    link: null,
    linkLabel: "Local project",
  },
  {
    title: "Retirement Simulation & Planning Model",
    description: "Built a Monte Carlo retirement model in Excel/VBA to estimate savings sustainability under changing returns, annual contributions, and retirement withdrawals across multiple scenarios.",
    icon: "🏦",
    tags: ["Excel", "VBA", "Financial Modeling"],
    link: null,
    linkLabel: "Local project",
  },
  {
    title: "Simulation for Smarter Operations",
    description: "Graduate simulation project focused on improving operational decisions under uncertainty. The analysis modeled system variability, measured performance trade-offs, and evaluated how process changes influence service levels, efficiency, and decision quality.",
    icon: "🧮",
    tags: ["Simulation", "Operations Research", "Process Improvement"],
    link: null,
    linkLabel: "Academic project",
  },
  {
    title: "OMSA Applied Practicum: Data-Driven Business Recommendation",
    description: "Applied industry project blending analytics, business context, and strategic recommendations to turn complex data into actionable decisions with measurable impact.",
    icon: "📊",
    tags: ["Business Analytics", "Strategy", "Data Insights"],
    link: null,
    linkLabel: "Master's project",
  },
  {
    title: "Team 149: Analytics Poster & Recommendation Sprint",
    description: "Collaborative capstone-style project translating analytical findings into a compelling executive-ready story, combining evidence, reasoning, and recommendation design for decision-makers.",
    icon: "🧠",
    tags: ["Data Storytelling", "Collaboration", "Research"],
    link: null,
    linkLabel: "Master's project",
  },
  {
    title: "P&G Strategic Equity Valuation",
    description: "Constructed a 3-statement financial model and DCF for Procter & Gamble, combining forecast building, valuation logic, and sensitivity analysis to estimate intrinsic value.",
    icon: "💹",
    tags: ["Excel", "DCF Valuation", "Financial Modeling"],
    link: null,
    linkLabel: "Local project",
  },
  {
    title: "Solar Flare Prediction App",
    description: "Interactive Streamlit model forecasting solar flare categories using magnetic and intensity-based inputs, turning physical measurements into a predictive classification tool.",
    icon: "🌞",
    tags: ["Streamlit", "Python", "Predictive Modeling"],
    link: null,
    linkLabel: "Local project",
  },
  {
    title: "COVID-19 Data Exploration (SQL)",
    description: "Advanced SQL analysis of infection, death, and vaccination trends using joins, CTEs, window functions, and views to uncover region-level insights and health patterns.",
    image: "images/covid.jpg",
    tags: ["SQL", "Data Exploration"],
    link: "https://github.com/PallaviSingh24/covid-EDA/blob/main/Covid_EDA%20by%20SQL",
    linkLabel: "View on GitHub",
  },
  {
    title: "Wine Quality Prediction (Python)",
    description: "Machine learning project on Vinho Verde wine data to predict quality using chemical composition and sensory features, comparing model performance across sample groups.",
    image: "images/wine.jpg",
    tags: ["Python", "Machine Learning"],
    link: "https://github.com/PallaviSingh24/Python-Project/blob/main/WineQuality.ipynb",
    linkLabel: "View on GitHub",
  },
];

const EXPERIENCE = [
  {
    title: "Project Cost Analyst Consultant",
    company: "SDG&E (Consultant)",
    period: "Jun 2022 – Present",
    bullets: [
      "Manage $50M+ in active project costs, strengthening accounting controls and driving process efficiencies across cross-functional teams.",
      "Own accruals, month-end close support, and cost forecasts for 8+ vendors, partnering with Project Managers to ensure accurate, on-time reporting.",
      "Built and maintain SQL Server infrastructure processing millions of multi-vendor timesheet records, powering dynamic Power BI dashboards for real-time cost and risk decisions.",
      "Automated vendor billing/timesheet validation, improving audit readiness through role-based data security controls.",
      "Deliver custom PM/BA dashboards (Power Query, Power Pivot) for variance tracking, scenario analysis, and month-end close reporting.",
      "Architect and refine automated financial workflows using AI coding tools (Claude, GitHub Copilot) and Python, moving reporting beyond manual data entry toward self-service, auto-flagged insights.",
    ],
  },
  {
    title: "Business Analyst Consultant",
    company: "Becton Dickinson",
    period: "Feb 2020 – Jul 2020",
    bullets: [
      "Extracted and consolidated data from SAP, Salesforce, and QlikView to track SKU performance across multiple regions.",
      "Partnered with Project Managers and stakeholders on deliverables, variance flags, and timeline alignment.",
      "Ran variance analysis and forecasting to support proactive financial planning.",
      "Quantified flu-season demand impact on product sales to inform inventory and marketing strategy.",
    ],
  },
  {
    title: "Business Analyst Consultant",
    company: "JSW",
    period: "Aug 2015 – Feb 2019",
    bullets: [
      "Performed variance analysis comparing actuals to budgets/forecasts, identifying root causes and key drivers.",
      "Delivered ad-hoc SQL/Excel financial and operational reports for PMs, BAs, and executive leadership.",
      "Built annual and monthly business plans aligned to corporate targets.",
      "Migrated static Excel reporting to interactive dashboards, improving data accessibility.",
      "Applied quality-control tools (control charts, Pareto charts, histograms) to surface performance outliers.",
    ],
  },
  {
    title: "Jr. Data Analyst Consultant",
    company: "JSW",
    period: "Aug 2014 – Aug 2015",
    bullets: [
      "Reviewed and processed invoices, ensuring accurate accounting classification per internal controls.",
      "Wrote SQL validation queries with complex joins to reconcile and verify datasets.",
      "Troubleshot Tableau dashboards for data accuracy and performance.",
    ],
  },
];
